### ISSUE TITLE
Can't clear map without explicit key

### ISSUE THREAD

**Issue by sugarraysam** [bpftrace/bpftrace#3548] opened 2024-10-28 23:41 UTC
### What reproduces the bug? Provide code if possible.

I want to be able to use map without explicit key, but dont want them to pollute the output at the end. The context is bpftrace is managed by an external process, that parses the output of the script, so any kind of pollution will cause issue in the expected output.

```bpftrace
#!/usr/bin/bpftrace

BEGIN {
    @myarg = 5;
}

END {
    clear(@myarg);
}
```

```bash
# Running the script will print the `@myarg`
$ sudo bpftrace test
Attaching 2 probes...
^C

@myarg: 0
```

### `bpftrace --info` output

System
  OS: Linux 5.19.0-0_fbk12_hardened_11583_g0bef9520ca2b #1 SMP Fri Feb 2 17:56:12 PST 2024
  Arch: x86_64

Build
  version: v0.21.0-80ca
  LLVM: 17.0.4
  bfd: yes
  liblldb (DWARF support): yes
  libsystemd (systemd notify support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: yes
  get_func_ip: yes
  jiffies64: yes
  for_each_map_elem: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: yes
  uprobe_multi: no
  raw_tp_special: yes
  iter: yes

**Comment by danobi** [comment] 2024-10-29 00:36
This will serve as a potentially good-enough workaround: https://github.com/bpftrace/bpftrace/pull/3547

We still want to solve delete()ing scalar maps, though.

Closing as dupe of #3498 - going to track there

**Closed by danobi** 2024-10-29 00:36 UTC
Labels: bug
