### ISSUE TITLE
tests: [  FAILED  ] json-output.histogram-finegrain

### ISSUE THREAD

**Issue by gkamathe** [bpftrace/bpftrace#3044] opened 2024-03-11 11:42 UTC
### What reproduces the bug? Provide code if possible.

Running the following test multiple times reproduces the error

```
./runtime-tests.sh --filter 'json-output.histogram-finegrain'
```

Error message

```
[  FAILED  ] json-output.histogram-finegrain
	Command: /home/test/bpftrace/build/src/bpftrace -q -f json -e 'i:us:100 { @ = hist(@n++,3); if (@n > 1023) { delete(@n); exit(); }}'
	Expected JSON:

< snip >

	Found:
Could not parse JSON: Extra data: line 4 column 1 (char 2400)
```

The test expects the following JSON

```
$ cat tests/runtime/outputs/hist_2args.json
{"type": "hist", "data": {"@": [{"min": 0, "max": 0, "count": 1}, {"min": 1, "max": 1, "count": 1}, {"min": 2, "max": 2, "count": 1}, {"min": 3, "max": 3, "count": 1}, {"min": 4, "max": 4, "count": 1}, {"min": 5, "max": 5, "count": 1}, {"min": 6, "max": 6, "count": 1}, {"min": 7, "max": 7, "count": 1}, {"min": 8, "max": 8, "count": 1}, {"min": 9, "max": 9, "count": 1}, {"min": 10, "max": 10, "count": 1}, {"min": 11, "max": 11, "count": 1}, {"min": 12, "max": 12, "count": 1}, {"min": 13, "max": 13, "count": 1}, {"min": 14, "max": 14, "count": 1}, {"min": 15, "max": 15, "count": 1}, {"min": 16, "max": 17, "count": 2}, {"min": 18, "max": 19, "count": 2}, {"min": 20, "max": 21, "count": 2}, {"min": 22, "max": 23, "count": 2}, {"min": 24, "max": 25, "count": 2}, {"min": 26, "max": 27, "count": 2}, {"min": 28, "max": 29, "count": 2}, {"min": 30, "max": 31, "count": 2}, {"min": 32, "max": 35, "count": 4}, {"min": 36, "max": 39, "count": 4}, {"min": 40, "max": 43, "count": 4}, {"min": 44, "max": 47, "count": 4}, {"min": 48, "max": 51, "count": 4}, {"min": 52, "max": 55, "count": 4}, {"min": 56, "max": 59, "count": 4}, {"min": 60, "max": 63, "count": 4}, {"min": 64, "max": 71, "count": 8}, {"min": 72, "max": 79, "count": 8}, {"min": 80, "max": 87, "count": 8}, {"min": 88, "max": 95, "count": 8}, {"min": 96, "max": 103, "count": 8}, {"min": 104, "max": 111, "count": 8}, {"min": 112, "max": 119, "count": 8}, {"min": 120, "max": 127, "count": 8}, {"min": 128, "max": 143, "count": 16}, {"min": 144, "max": 159, "count": 16}, {"min": 160, "max": 175, "count": 16}, {"min": 176, "max": 191, "count": 16}, {"min": 192, "max": 207, "count": 16}, {"min": 208, "max": 223, "count": 16}, {"min": 224, "max": 239, "count": 16}, {"min": 240, "max": 255, "count": 16}, {"min": 256, "max": 287, "count": 32}, {"min": 288, "max": 319, "count": 32}, {"min": 320, "max": 351, "count": 32}, {"min": 352, "max": 383, "count": 32}, {"min": 384, "max": 415, "count": 32}, {"min": 416, "max": 447, "count": 32}, {"min": 448, "max": 479, "count": 32}, {"min": 480, "max": 511, "count": 32}, {"min": 512, "max": 575, "count": 64}, {"min": 576, "max": 639, "count": 64}, {"min": 640, "max": 703, "count": 64}, {"min": 704, "max": 767, "count": 64}, {"min": 768, "max": 831, "count": 64}, {"min": 832, "max": 895, "count": 64}, {"min": 896, "max": 959, "count": 64}, {"min": 960, "max": 1023, "count": 64}]}}
```

Based on this check

```
226  	        def check_result(output):
227  	            all_passed = True
228  	            for expect in test.expects:
229  ->	                if not check_expect(expect, output):
230  	                    all_passed = False
231  	                    failed_expects.append(expect)
232  	            return all_passed
```

However the command line produces the following

```
$ sudo ./src/bpftrace -q -f json -e 'i:us:100 { @ = hist(@n++,3); if (@n > 1023) { delete(@n); exit(); }}'


{"type": "hist", "data": {"@": [{"min": 0, "max": 0, "count": 2}, {"min": 1, "max": 1, "count": 1}, {"min": 2, "max": 2, "count": 1}, {"min": 3, "max": 3, "count": 1}, {"min": 4, "max": 4, "count": 1}, {"min": 5, "max": 5, "count": 1}, {"min": 6, "max": 6, "count": 1}, {"min": 7, "max": 7, "count": 1}, {"min": 8, "max": 8, "count": 1}, {"min": 9, "max": 9, "count": 1}, {"min": 10, "max": 10, "count": 1}, {"min": 11, "max": 11, "count": 1}, {"min": 12, "max": 12, "count": 1}, {"min": 13, "max": 13, "count": 1}, {"min": 14, "max": 14, "count": 1}, {"min": 15, "max": 15, "count": 1}, {"min": 16, "max": 17, "count": 2}, {"min": 18, "max": 19, "count": 2}, {"min": 20, "max": 21, "count": 2}, {"min": 22, "max": 23, "count": 2}, {"min": 24, "max": 25, "count": 2}, {"min": 26, "max": 27, "count": 2}, {"min": 28, "max": 29, "count": 2}, {"min": 30, "max": 31, "count": 2}, {"min": 32, "max": 35, "count": 4}, {"min": 36, "max": 39, "count": 4}, {"min": 40, "max": 43, "count": 4}, {"min": 44, "max": 47, "count": 4}, {"min": 48, "max": 51, "count": 4}, {"min": 52, "max": 55, "count": 4}, {"min": 56, "max": 59, "count": 4}, {"min": 60, "max": 63, "count": 4}, {"min": 64, "max": 71, "count": 8}, {"min": 72, "max": 79, "count": 8}, {"min": 80, "max": 87, "count": 8}, {"min": 88, "max": 95, "count": 8}, {"min": 96, "max": 103, "count": 8}, {"min": 104, "max": 111, "count": 8}, {"min": 112, "max": 119, "count": 8}, {"min": 120, "max": 127, "count": 8}, {"min": 128, "max": 143, "count": 16}, {"min": 144, "max": 159, "count": 16}, {"min": 160, "max": 175, "count": 16}, {"min": 176, "max": 191, "count": 16}, {"min": 192, "max": 207, "count": 16}, {"min": 208, "max": 223, "count": 16}, {"min": 224, "max": 239, "count": 16}, {"min": 240, "max": 255, "count": 16}, {"min": 256, "max": 287, "count": 32}, {"min": 288, "max": 319, "count": 32}, {"min": 320, "max": 351, "count": 32}, {"min": 352, "max": 383, "count": 32}, {"min": 384, "max": 415, "count": 32}, {"min": 416, "max": 447, "count": 32}, {"min": 448, "max": 479, "count": 32}, {"min": 480, "max": 511, "count": 32}, {"min": 512, "max": 575, "count": 64}, {"min": 576, "max": 639, "count": 64}, {"min": 640, "max": 703, "count": 64}, {"min": 704, "max": 767, "count": 64}, {"min": 768, "max": 831, "count": 64}, {"min": 832, "max": 895, "count": 64}, {"min": 896, "max": 959, "count": 64}, {"min": 960, "max": 1023, "count": 64}]}}
{"type": "map", "data": {"@n": 1}}
```

Notice there is an extra data towards the end 

```
{"type": "map", "data": {"@n": 1}}
```

Which is what the above error message states

```
Could not parse JSON: Extra data: line 4 column 1 (char 2400)
```

### `bpftrace --info` output

```
$ ./src/bpftrace --info
System
  OS: Linux 6.7.7-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar  1 16:51:49 UTC 2024
  Arch: x86_64

Build
  version: v0.20.0-62-g6a41
  LLVM: 16.0.6
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: yes
  get_func_ip: yes
  jiffies64: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: yes
  uprobe_multi: no
  raw_tp_special: yes
  iter: yes

```

**Comment by viktormalik** [comment] 2024-03-11 12:00
Duplicate of #3035.

**Closed by viktormalik** 2024-03-11 12:00 UTC
Labels: bug
