### ISSUE TITLE
Select per cpu variables from kaddr

### ISSUE THREAD

**Issue by glemco** [bpftrace/bpftrace#3579] opened 2024-11-07 14:38 UTC
### Is your feature request related to a problem? Please describe.

Some kernel addresses are related to per-cpu variables, these have in turn offsets depending on the current cpu, usually optimised for access speed (https://www.kernel.org/doc/html/latest/core-api/this_cpu_ops.html).

There is currently no way to get the address of a per-cpu variable in `bpftrace`.

### Describe the solution you'd like

Take as an example the per-cpu variable `per_cpu_timerlat_var`, it would be handy to use it in bpftrace with something like.
```awk
/var == per_cpu_ptr(kaddr("per_cpu_timerlat_var"), cpu)/
```
Where the function `per_cpu_ptr` could be implemented directly with [bpf_per_cpu_ptr](https://docs.ebpf.io/linux/helper-function/bpf_per_cpu_ptr/).

### Describe alternative solutions or features you've considered

Depending on the variable, there may be a different way to set up a condition (e.g. in the example above, instead of looking for `per_cpu_timerlat_var->timer`, one may use the timer function in `t:timer:hrtimer_start`) but this may not always be applicable or easy.

**Comment by danobi** [comment] 2024-11-07 19:28
Agreed, we should support this.

However, closing as dupe of https://github.com/bpftrace/bpftrace/issues/1837. We're now using libbpf to load our progs, so maybe it's unblocked. Will move discussion to earlier issue.

**Closed by danobi** 2024-11-07 19:28 UTC
Labels: enhancement
